
# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.output_dir}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.output_dir}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${oc.select:hydra.job.num,0}

job_logging:
  root:
    level: INFO
  # colorlog will set two formatters: simple and colorlog. We just override the format for simple which is for file.
  formatters:
    simple:
      format: '[%(asctime)s][%(name)s:%(lineno)d][%(levelname)s] - %(message)s'
    colorlog:
      format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s:%(lineno)d%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra:runtime.output_dir}/job.log
      mode: a # we want to append when resuming
      formatter: simple
  loggers:
    __main__:
      level: INFO
    datasets:
      level: INFO
    datasets.arrow_dataset:
      level: INFO

job:
  env_set:
    PROJECT_ROOT: "."
    HF_HOME: "/work/pi_mccallum_umass_edu/dhruveshpate_umass_edu/hf_cache"
    TQDM_MINITERS: 100 # lightning uses this