# @package _global_

lightning_module:
  _target_: pcdd.diffusion.ilm_v2.ILMLightningModule

loss:
  _target_: pcdd.diffusion.ilm_v2.ILMLossWithMaskedCEForWrappedPaddedSequences
  loss_on_padding: false

predictor:
  _target_: pcdd.diffusion.ilm_v2.ILMPredictor
  tokenizer: ${lightning_module:tokenizer}
  noise_schedule: ${lightning_module:noise_schedule}
  max_steps: ??? # depends on the dataset
  max_length: ??? # depends on the dataset
  sampling_method: sample

tags:
  model_type: ilm