# @package _global_

lightning_module:
  _target_: pcdd.diffusion.ilm_v2.ILMWithStoppingClassificationLightningModule

loss:
  _target_: pcdd.diffusion.ilm_v2.ILMWithStoppingClassificationLossWithMaskedCE
  loss_on_padding: false

predictor:
  _target_: pcdd.diffusion.ilm_v2.ILMPredictorWithStoppingClassification
  tokenizer: ${lightning_module:tokenizer}
  noise_schedule: ${lightning_module:noise_schedule}
  max_steps: ??? # depends on the dataset
  max_length: ??? # depends on the dataset
  sampling_method: sample_top_p
  p: 0.5
  second_sampling_method: sample_top_k
  second_top: 1

tags:
  model_type: ilm_stopping