# @package _global_

lightning_module:
  _target_: pcdd.diffusion.mlm.MLMLightningModule

loss:
  _target_: pcdd.diffusion.mlm.MLMLoss
  loss_on_padding: true
  loss_on_visible_tokens: true

predictor:
  _target_: pcdd.diffusion.mlm.MLMPredictor
  tokenizer: ${lightning_module:tokenizer}
  noise_schedule: ${lightning_module:noise_schedule}
  max_steps: ??? # depends on the dataset
  max_length: ??? # depends on the dataset
  sampling_method: sample

tags:
  model_type: mlm