tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: ${paths.output_dir}/tensorboard
  name: null
  version: null
  log_graph: False
  default_hp_metric: True
  prefix: ""