defaults:
  - lm1b

_target_: pcdd.datamodule.lm1b.LM1BForARLMDataModule
tokenizer:
  _target_: pcdd.datamodule.datamodule.BertTokenizerForARLMFast.from_pretrained
  pretrained_model_name_or_path: bert-base-uncased
