defaults:
  - lm1b

_target_: pcdd.datamodule.stories.StoriesForILMStoppingDataModule
tokenizer:
  _target_: pcdd.datamodule.datamodule.BertTokenizerForILMFast.from_pretrained
  pretrained_model_name_or_path: bert-base-uncased

global_batch_size: 512
block_size: 1024