defaults:
  - lm1b

_target_: pcdd.datamodule.stories.StoriesForMDLMDataModule
tokenizer:
  _target_: pcdd.datamodule.datamodule.BertTokenizerForMDLMFast.from_pretrained
  pretrained_model_name_or_path: bert-base-uncased

block_size: 1024