defaults:
  - lm1b

_target_: pcdd.datamodule.lm1b.LM1BForMDLMDataModule
tokenizer:
  _target_: pcdd.datamodule.datamodule.BertTokenizerForMDLMFast.from_pretrained
  pretrained_model_name_or_path: bert-base-uncased