_target_: pcdd.datamodule.StarGraphDataModule
manual_cache_dir: ${oc.env:DATA_DIR, data}
global_batch_size: ${.train_dataloader_kwargs.batch_size}
tokenizer: 
  _target_: pcdd.datamodule.star.SimpleSpaceTokenizer
  vocab_size: 128
train_dataloader_kwargs:
  batch_size:  64 # per device, depends on the device type
  num_workers: ${oc.decode:${oc.env:SLURM_CPUS_PER_TASK,4}} 
  shuffle: True
  pin_memory: True
  persistent_workers: True
  prefetch_factor: 5
  drop_last: True
val_dataloader_kwargs:
  batch_size: ${..train_dataloader_kwargs.batch_size} # same as training batch size to avoid recompilation
  num_workers: ${..train_dataloader_kwargs.num_workers}
  shuffle: False
  pin_memory: ${..train_dataloader_kwargs.pin_memory}
  persistent_workers: ${..train_dataloader_kwargs.persistent_workers}
  drop_last: True
test_dataloader_kwargs: 
  batch_size: ${..train_dataloader_kwargs.batch_size}
  num_workers: ${..train_dataloader_kwargs.num_workers}
  shuffle: False
  pin_memory: ${..train_dataloader_kwargs.pin_memory}
  persistent_workers: ${..train_dataloader_kwargs.persistent_workers}
  drop_last: True

block_size: 128 # set by dataset
collation_strategy: pad_truncate # set by dataset
rewrite_manual_cache: false