# @package _global_
# four nodes, one gpu per node

slurm:
  nodes: 1
  gres: gpu:1
  ntasks_per_node: 1
  constrain: "vram80,bf16"  # ib for infiniband
  partition: gpu,gpu-preempt,superpod-a100
  time: 1-00:00:00