# @package _global_
compile: true
trainer:
  num_sanity_val_steps: 0
  val_check_interval: ${.max_steps} # only run eval once at the end
  check_val_every_n_epoch: null
  precision: bf16-mixed

generative_perplexity:
  evaluators: null

hydra:
  job:
    env_set:
      TQDM_MINITERS: 1000

tags:
  fast_run: true
  precision: bf16-mixed
  compile: true