# @package _global_
defaults:
  - small_data_v2
  #- /callbacks/checkpoint_every_n_steps_with_thinning
global_flags:
  DEBUG_OVERFIT: true

paths:
  log_dir: ${paths.root_dir}/debug_logs/overfit_star_v2

datamodule:
  global_batch_size: 1
  train_dataloader_kwargs:
    num_workers: 0
    batch_size: 1
    pin_memory: false
    persistent_workers: false
    prefetch_factor: null

trainer:
  max_epochs: null
  max_steps: 30000 #1000_000
  overfit_batches: 1 #800 # 500
  val_check_interval: 100 #null # 5000
  check_val_every_n_epoch: null #1
  log_every_n_steps: 1
  gradient_clip_val: 1.0
  enable_checkpointing: null

lr_scheduler:
  num_warmup_steps: 10

generative_perplexity:
  evaluators: null
  num_samples: 1
