# @package _global_
defaults:
  - override /callbacks: debug
  - override /loggers: debug

paths:
  log_dir: ${paths.root_dir}/debug_logs

global_flags:
  DEBUG: true

datamodule:
  num_dataset_workers: 1 # does not accept 0
  global_batch_size: 10
  train_dataloader_kwargs:
    num_workers: 0
    batch_size: 10
  val_dataloader_kwargs:
    num_workers: 0
    batch_size: 10

trainer:
  log_every_n_steps: 1
  limit_train_batches: 100
  limit_val_batches: 100
  limit_test_batches: 100
  enable_checkpointing: false
  val_check_interval: 50

tags:
  debug: true

hydra:
  job:
    env_set:
      TQDM_MINITERS: 1 # Print every step while debugging
  job_logging:
    loggers:
      __main__:
        level: DEBUG
      datasets:
        level: DEBUG
      datasets.arrow_dataset:
        level: DEBUG
