# @package _global_


model:
  _target_: pcdd.models.d3pm.AbsorbingDDiTD3PMModel
  num_embeddings: ${tokenizer:vocab_size}
  d_model: 768
  num_layers: 12
  nhead: 12
  padding_idx: ${tokenizer:pad_token_id}
  mask_idx: ${tokenizer:mask_token_id}
  dim_feedforward: 3072
  dropout: 0.1
  activation: "relu"
  layer_norm_eps: 1e-5
  d_cond: 384

tags:
  model: absorbing_ddit_small