# @package _global_


model:
  _target_: pcdd.models.ilm.GPT2ILMModel
  num_embeddings: ${tokenizer:full_vocab_size}
  d_model: 768 # mdlm
  num_layers: 12
  nhead: 12
  padding_idx: ${tokenizer:pad_token_id}
  mask_idx: ${tokenizer:mask_token_id}
  dim_feedforward: ${eval:${.d_model}*4}
  dropout: 0.1
  activation: "gelu"
  max_length: ${predictor.max_length}

tags:
  model: gpt2_small
  length_model: none